# This is a basic workflow to help you get started with Actions

name: Get Stars

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install dependecies
        run: pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: run script
        run: python stargazers.py --repo scribe_public/gitgat -t ${{ secrets.GITHUB_TOKEN }} --output-type csv -o gitgat_stars.csv
        
      - name: uplaod artifact before buidling the app
        uses: actions/upload-artifact@v3
        with:
          name: upload csv file
          path: gitgat_stars.csv
          
          
          
